--creating warehouse import_wh
CREATE WAREHOUSE IMPORT_WH
WITH WAREHOUSE_SIZE = 'MEDIUM'
WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 300 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 
INITIALLY_SUSPENDED = TRUE
AUTO_RESUME = TRUE;


--creating warehouse transform_wh
CREATE WAREHOUSE TRANSFORM_WH
WITH WAREHOUSE_SIZE = 'MEDIUM'
WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 300 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 
INITIALLY_SUSPENDED = TRUE
AUTO_RESUME = TRUE;


--creating warehouse reporting_wh
CREATE WAREHOUSE REPORTING_WH
WITH WAREHOUSE_SIZE = 'SMALL'
WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 900 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 5 
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

show warehouses;


--creating databases staging and prod
CREATE DATABASE STAGING;
CREATE DATABASE PROD;

show databases;


--creating schemas for database staging with data retention=3
CREATE SCHEMA STAGING.RAW 
DATA_RETENTION_TIME_IN_DAYS = 3
COMMENT = '(Default Data Retension 3 days for tables to keep
original raw data as it is ingested)';

CREATE SCHEMA STAGING.CLEAN
DATA_RETENTION_TIME_IN_DAYS = 3
COMMENT = '(Default Data Retension 3 days for tables to
keep cleaned data for ETL & modeling & ETL)';


--creating schema for database prod with data retention=90
CREATE SCHEMA PROD.REPORTING
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = '(Used by Business Users for analytics 
& keeps 90 day continous history)';

show schemas in staging;
show schemas in prod;


--creating roles and providing access to specific warehouses, databases and schemas.
CREATE ROLE IMPORT_ROLE;

GRANT USAGE ON WAREHOUSE IMPORT_WH TO ROLE IMPORT_ROLE;
GRANT USAGE ON DATABASE STAGING TO ROLE IMPORT_ROLE;  

GRANT USAGE ON SCHEMA STAGING.RAW TO ROLE IMPORT_ROLE; 
GRANT USAGE ON SCHEMA STAGING.CLEAN TO ROLE IMPORT_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA STAGING.RAW TO ROLE IMPORT_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA STAGING.CLEAN TO ROLE IMPORT_ROLE;

--GRANT USAGE ON STAGE STAGING_SOURCE TO ROLE IMPORT_ROLE;



--creating 2nd role
CREATE ROLE TRANSFORM_ROLE;

GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORM_ROLE;
GRANT USAGE ON DATABASE STAGING TO ROLE TRANSFORM_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA STAGING.CLEAN TO ROLE TRANSFORM_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PROD.REPORTING TO ROLE TRANSFORM_ROLE;


--creating 3rd role
CREATE ROLE REPORTING_ROLE;

GRANT USAGE ON WAREHOUSE REPORTING_WH TO ROLE REPORTING_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA PROD.REPORTING TO ROLE REPORTING_ROLE;

show roles;


--creating users with their default roles and passwords.
CREATE USER USERREPORTING PASSWORD = 'USERREPORT' LOGIN_NAME = 'RR' DEFAULT_ROLE='REPORTING_ROLE'  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER USERTRANSFORM PASSWORD = 'USERTRANSFORM' LOGIN_NAME = 'UTR' DEFAULT_ROLE='TRANSFORM_ROLE'  MUST_CHANGE_PASSWORD = FALSE;

CREATE USER USERIMPORT PASSWORD = 'USERIMPORT' LOGIN_NAME = 'UI' 
DEFAULT_ROLE='IMPORT_ROLE'  MUST_CHANGE_PASSWORD = FALSE;

show users;


--creating resource monitors with 100 credits a month
CREATE RESOURCE MONITOR IMPORT_MONITOR WITH
                      CREDIT_QUOTA = 100
                      FREQUENCY = MONTHLY
                      START_TIMESTAMP = IMMEDIATELY;

CREATE RESOURCE MONITOR TRANSFORM_MONITOR WITH
                      CREDIT_QUOTA = 100
                      FREQUENCY = MONTHLY
                      START_TIMESTAMP = IMMEDIATELY;

CREATE RESOURCE MONITOR REPORTING_MONITOR WITH
                      CREDIT_QUOTA = 100
                      FREQUENCY = MONTHLY
                      START_TIMESTAMP = IMMEDIATELY;

show resource monitors;